***19B01A1230***  
***CH.JAHNAVI***    
***11-04-2022***



# **1. Write python program for consider two random array A and B, check if they are equal.**

In [14]:
import numpy as np
a = np.random.randint(1,10,5)
print("First array:")
print(a)
b = np.random.randint(1,10,5)
print("Second array:")
print(b)
print("Test above two arrays are equal or not!")
result = np.allclose(a, b)
print(result)


First array:
[1 9 8 9 4]
Second array:
[4 9 3 2 5]
Test above two arrays are equal or not!
False


# **2. Write python program for consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [3]:
import numpy as np

Z = np.ones(10)
print("Ones Array: ",Z)
length=len(Z)
print("Length: ",length)

I = np.random.randint(0,length,20)
print("Random Array: ",I)
I_length=len(I)
print("Length: ",I_length)

Z += np.bincount(I, minlength=len(Z))
print("Result: ",Z)

Ones Array:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Length:  10
Random Array:  [9 1 3 0 0 4 6 3 1 1 7 6 0 8 3 2 5 6 2 8]
Length:  20
Result:  [4. 4. 3. 4. 2. 2. 4. 2. 3. 2.]


# **3. Write python program to get the n largest values of an array.**

In [4]:
import numpy as np

Arr = np.random.randint(0,50,20)

print("Array Elements: ",Arr)


n = int(input("How many largest Numbers you need: "))

# Slow
print (n," Largest values from Array", Arr[np.argsort(Arr)[-n:]])

# Fast
print (n," Largest values from Array", Arr[np.argpartition(-Arr,n)[:n]])

Array Elements:  [10 33 46 19 28 25 41 14 10 35 47 21 40 47 31 21 45 26  8  8]
How many largest Numbers you need: 12
12  Largest values from Array [25 26 28 31 33 35 40 41 45 46 47 47]
12  Largest values from Array [40 45 46 31 28 25 41 35 26 33 47 47]


## **4.Load the energy data from the file Energy Indicators.xls, which is a list of indicators of[energy supply and renewable electricity production] (Energy%20Indicators.xls) from the Dataset (http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of energy.**

In [4]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [5]:
url='http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls'
energy=pd.read_excel(url)


In [6]:
energy

Unnamed: 0                                         Unnamed: 1  \
0           NaN                                                NaN   
1           NaN                                                NaN   
2           NaN                                                NaN   
3           NaN                                                NaN   
4           NaN                                                NaN   
..          ...                                                ...   
277         NaN                       … denotes no data available.   
278         NaN                                                NaN   
279         NaN                                     Data Quality:    
280         NaN  The data are compiled primarily from the annua...   
281         NaN  For more information, visit http://unstats.un....   

                                            Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0                     Environmental Indicators: Energy        NaN        NaN   
1                                                  NaN        NaN        NaN   
2    Energy Supply and Renewable Electricity Produc...        NaN        NaN   
3                                                  NaN        NaN        NaN   
4                                                  NaN        NaN        NaN   
..                                                 ...        ...        ...   
277                                                NaN        NaN        NaN   
278                                                NaN        NaN        NaN   
279                                                NaN        NaN        NaN   
280                                                NaN        NaN        NaN   
281                                                NaN        NaN        NaN   

                     Unnamed: 5  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4    Last update: December 2015  
..                          ...  
277                         NaN  
278                         NaN  
279                         NaN  
280                         NaN  
281                         NaN  

[282 rows x 6 columns]

In [7]:
energy = energy.drop(energy.columns[0:2], axis = 1)
energy

Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0                     Environmental Indicators: Energy        NaN        NaN   
1                                                  NaN        NaN        NaN   
2    Energy Supply and Renewable Electricity Produc...        NaN        NaN   
3                                                  NaN        NaN        NaN   
4                                                  NaN        NaN        NaN   
..                                                 ...        ...        ...   
277                                                NaN        NaN        NaN   
278                                                NaN        NaN        NaN   
279                                                NaN        NaN        NaN   
280                                                NaN        NaN        NaN   
281                                                NaN        NaN        NaN   

                     Unnamed: 5  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4    Last update: December 2015  
..                          ...  
277                         NaN  
278                         NaN  
279                         NaN  
280                         NaN  
281                         NaN  

[282 rows x 4 columns]

In [8]:
energy.head(10)

Unnamed: 2     Unnamed: 3  \
0                   Environmental Indicators: Energy            NaN   
1                                                NaN            NaN   
2  Energy Supply and Renewable Electricity Produc...            NaN   
3                                                NaN            NaN   
4                                                NaN            NaN   
5                                                NaN            NaN   
6  Choose a country from the following drop-down ...            NaN   
7                                                NaN            NaN   
8                                            Country  Energy Supply   
9                                                NaN     Petajoules   

                 Unnamed: 4                        Unnamed: 5  
0                       NaN                               NaN  
1                       NaN                               NaN  
2                       NaN                               NaN  
3                       NaN                               NaN  
4                       NaN        Last update: December 2015  
5                       NaN                               NaN  
6                       NaN                       Afghanistan  
7                       NaN                               NaN  
8  Energy Supply per capita  Renewable Electricity Production  
9                Gigajoules                                 %

In [9]:
energy.tail(50)

Unnamed: 2 Unnamed: 3 Unnamed: 4  \
232                        United Republic of Tanzania        994         20   
233                         United States of America20      90838        286   
234                       United States Virgin Islands        ...        ...   
235                                            Uruguay        196         58   
236                                         Uzbekistan       1798         62   
237                                            Vanuatu          3         10   
238                 Venezuela (Bolivarian Republic of)       2871         95   
239                                           Viet Nam       2554         28   
240                          Wallis and Futuna Islands          0         26   
241                                              Yemen        344         13   
242                                             Zambia        400         26   
243                                           Zimbabwe        480         32   
244                                                NaN        NaN        NaN   
245                                                NaN        NaN        NaN   
246                                                NaN        NaN        NaN   
247                                                NaN        NaN        NaN   
248                                                NaN        NaN        NaN   
249                                                NaN        NaN        NaN   
250                                                NaN        NaN        NaN   
251                 Excludes the overseas territories.        NaN        NaN   
252  Data exclude Hong Kong and Macao Special Admin...        NaN        NaN   
253  Data on kerosene-type jet fuel include aviatio...        NaN        NaN   
254  For confidentiality reasons, data on coal and ...        NaN        NaN   
255      Data exclude Greenland and the Danish Faroes.        NaN        NaN   
256  Data include Monaco, and exclude the following...        NaN        NaN   
257  Data for kerosene-type jet fuel include other ...        NaN        NaN   
258               Data include Timor-Leste until 2001.        NaN        NaN   
259         Data include San Marino and the Holy See.         NaN        NaN   
260                              Data include Okinawa.        NaN        NaN   
261  The data for crude oil production include 50 p...        NaN        NaN   
262  Data exclude Suriname and the Netherlands Anti...        NaN        NaN   
263               Data include the Azores and Madeira.        NaN        NaN   
264  Data for crude oil production include 50 per c...        NaN        NaN   
265             Data exclude Kosovo from 2000 onwards.        NaN        NaN   
266                   Data include the Canary Islands.        NaN        NaN   
267     Data include Liechtenstein for oil statistics.        NaN        NaN   
268  For confidentiality reasons, data on the follo...        NaN        NaN   
269  Shipments of coal and oil to Jersey, Guernsey ...        NaN        NaN   
270  Includes the 50 states and the District of Col...        NaN        NaN   
271                                                NaN        NaN        NaN   
272                                                NaN        NaN        NaN   
273                                                NaN        NaN        NaN   
274                                                NaN        NaN        NaN   
275                                                NaN        NaN        NaN   
276                                                NaN        NaN        NaN   
277                                                NaN        NaN        NaN   
278                                                NaN        NaN        NaN   
279                                                NaN        NaN        NaN   
280                                                NaN        NaN        NaN   
281                                         

In [18]:
energy = energy[9:243]
new_header = ['Country', 'Energy Supply', 'Energy Supply per Capita', 'Renewable Electricity Production']
energy.columns = new_header
energy

Country Energy Supply  \
27                                Aruba            12   
28                           Australia1          5386   
29                              Austria          1391   
30                           Azerbaijan           567   
31                              Bahamas            45   
..                                  ...           ...   
238  Venezuela (Bolivarian Republic of)          2871   
239                            Viet Nam          2554   
240           Wallis and Futuna Islands             0   
241                               Yemen           344   
242                              Zambia           400   

    Energy Supply per Capita Renewable Electricity Production  
27                       120                         14.87069  
28                       231                         11.81081  
29                       164                         72.45282  
30                        60                         6.384345  
31                       118                                0  
..                       ...                              ...  
238                       95                         67.83452  
239                       28                         45.32152  
240                       26                                0  
241                       13                                0  
242                       26                         99.71467  

[216 rows x 4 columns]

In [19]:
energy.replace('...', np.nan,inplace = True)
energy

Country  Energy Supply  \
27                                Aruba           12.0   
28                           Australia1         5386.0   
29                              Austria         1391.0   
30                           Azerbaijan          567.0   
31                              Bahamas           45.0   
..                                  ...            ...   
238  Venezuela (Bolivarian Republic of)         2871.0   
239                            Viet Nam         2554.0   
240           Wallis and Futuna Islands            0.0   
241                               Yemen          344.0   
242                              Zambia          400.0   

     Energy Supply per Capita  Renewable Electricity Production  
27                      120.0                         14.870690  
28                      231.0                         11.810810  
29                      164.0                         72.452820  
30                       60.0                          6.384345  
31                      118.0                          0.000000  
..                        ...                               ...  
238                      95.0                         67.834520  
239                      28.0                         45.321520  
240                      26.0                          0.000000  
241                      13.0                          0.000000  
242                      26.0                         99.714670  

[216 rows x 4 columns]

In [20]:
energy.Country.replace(r'\s\([^()]*\)', '', regex = True, inplace = True) # s for space before parenthesis
energy.Country.replace(r'\d+', '', regex = True, inplace = True)
energy

Country  Energy Supply  Energy Supply per Capita  \
27                       Aruba           12.0                     120.0   
28                   Australia         5386.0                     231.0   
29                     Austria         1391.0                     164.0   
30                  Azerbaijan          567.0                      60.0   
31                     Bahamas           45.0                     118.0   
..                         ...            ...                       ...   
238                  Venezuela         2871.0                      95.0   
239                   Viet Nam         2554.0                      28.0   
240  Wallis and Futuna Islands            0.0                      26.0   
241                      Yemen          344.0                      13.0   
242                     Zambia          400.0                      26.0   

     Renewable Electricity Production  
27                          14.870690  
28                          11.810810  
29                          72.452820  
30                           6.384345  
31                           0.000000  
..                                ...  
238                         67.834520  
239                         45.321520  
240                          0.000000  
241                          0.000000  
242                         99.714670  

[216 rows x 4 columns]

In [22]:
energy['Energy Supply'] *= 1000000
energy

Country  Energy Supply  Energy Supply per Capita  \
27                       Aruba   1.200000e+07                     120.0   
28                   Australia   5.386000e+09                     231.0   
29                     Austria   1.391000e+09                     164.0   
30                  Azerbaijan   5.670000e+08                      60.0   
31                     Bahamas   4.500000e+07                     118.0   
..                         ...            ...                       ...   
238                  Venezuela   2.871000e+09                      95.0   
239                   Viet Nam   2.554000e+09                      28.0   
240  Wallis and Futuna Islands   0.000000e+00                      26.0   
241                      Yemen   3.440000e+08                      13.0   
242                     Zambia   4.000000e+08                      26.0   

     Renewable Electricity Production  
27                          14.870690  
28                          11.810810  
29                          72.452820  
30                           6.384345  
31                           0.000000  
..                                ...  
238                         67.834520  
239                         45.321520  
240                          0.000000  
241                          0.000000  
242                         99.714670  

[216 rows x 4 columns]

In [23]:
country_name = {"Republic of Korea": "South Korea", 
                "United States of America": "United States",
                "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
                "China, Hong Kong Special Administrative Region": "Hong Kong"}
energy.Country = energy.Country.replace(country_name)
energy

Country  Energy Supply  Energy Supply per Capita  \
27                       Aruba   1.200000e+07                     120.0   
28                   Australia   5.386000e+09                     231.0   
29                     Austria   1.391000e+09                     164.0   
30                  Azerbaijan   5.670000e+08                      60.0   
31                     Bahamas   4.500000e+07                     118.0   
..                         ...            ...                       ...   
238                  Venezuela   2.871000e+09                      95.0   
239                   Viet Nam   2.554000e+09                      28.0   
240  Wallis and Futuna Islands   0.000000e+00                      26.0   
241                      Yemen   3.440000e+08                      13.0   
242                     Zambia   4.000000e+08                      26.0   

     Renewable Electricity Production  
27                          14.870690  
28                          11.810810  
29                          72.452820  
30                           6.384345  
31                           0.000000  
..                                ...  
238                         67.834520  
239                         45.321520  
240                          0.000000  
241                          0.000000  
242                         99.714670  

[216 rows x 4 columns]

***19B01A1230***     
***CH.JAHNAVI***         
***18-04-2022***

# **5. Write python program for given an arbitrary number of vectors, build the cartesian product (every combinations of every item).**

In [10]:
# For two arrays
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5])
res = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])
print("Cartesian Product for Two Arrays:")
print(res)

Cartesian Product for Two Arrays:
[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]]


In [13]:
# For Multiple Arrays
import numpy as np
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    print("Arrays: \n",arrays)
    
    shape = (len(x) for x in arrays)
    

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

arr1=[1, 2, 3]
arr2=[4,5]
arr3=[6,7]
arr4=[8,9,0]
res=cartesian((arr1, arr2, arr3,arr4))
print("Cartesian Product for Multiple Arrays: \n", res)



Arrays: 
 [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9, 0])]
Cartesian Product for Multiple Arrays: 
 [[1 4 6 8]
 [1 4 6 9]
 [1 4 6 0]
 [1 4 7 8]
 [1 4 7 9]
 [1 4 7 0]
 [1 5 6 8]
 [1 5 6 9]
 [1 5 6 0]
 [1 5 7 8]
 [1 5 7 9]
 [1 5 7 0]
 [2 4 6 8]
 [2 4 6 9]
 [2 4 6 0]
 [2 4 7 8]
 [2 4 7 9]
 [2 4 7 0]
 [2 5 6 8]
 [2 5 6 9]
 [2 5 6 0]
 [2 5 7 8]
 [2 5 7 9]
 [2 5 7 0]
 [3 4 6 8]
 [3 4 6 9]
 [3 4 6 0]
 [3 4 7 8]
 [3 4 7 9]
 [3 4 7 0]
 [3 5 6 8]
 [3 5 6 9]
 [3 5 6 0]
 [3 5 7 8]
 [3 5 7 9]
 [3 5 7 0]]


# **6. Write python program to get value of x for given linear equations.**

In [12]:
from sympy import symbols, Eq, solve
x, y, z = symbols('x,y,z')
eq1 = Eq((x+y+z), 1)
print("Equation 1: ", eq1)
eq2 = Eq((x-y+2*z), 1)
print("Equation 2: ",eq2)
eq3 = Eq((2*x-y+2*z), 1)
print("Equation 3: ",eq3)
print("\n Values of 3 unknown variable are as follows:")
print(solve((eq1, eq2, eq3), (x, y, z)))


Equation 1:  Eq(x + y + z, 1)
Equation 2:  Eq(x - y + 2*z, 1)
Equation 3:  Eq(2*x - y + 2*z, 1)

 Values of 3 unknown variable are as follows:
{x: 0, y: 1/3, z: 2/3}


# **7. Write python program to find eigen analysis for given matrix.**


In [24]:
import numpy as np
m = np.array([[1, 2, 4],
              [2, 4, 8],
              [4, 8, 9]])

print("Printing the Original square array:\n",m)
w, v = np.linalg.eig(m)

print("Printing the Eigen values of the given square array:\n",w)

print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Original square array:
 [[1 2 4]
 [2 4 8]
 [4 8 9]]
Printing the Eigen values of the given square array:
 [ 1.61651514e+01  1.71944109e-16 -2.16515139e+00]
Printing Right eigenvectors of the given square array:
 [[-2.79603668e-01 -8.94427191e-01 -3.49029782e-01]
 [-5.59207335e-01  4.47213595e-01 -6.98059565e-01]
 [-7.80454320e-01 -1.43996363e-16  6.25212808e-01]]
